config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
     get '/register_type', to: 'users/registrations#register_type', as: 'register_type'
     get '/new_volunteer', to: 'users/registrations#new_volunteer', as: 'new_volunteer'
     get '/new_organization', to: 'users/registrations#new_organization', as: 'new_organization'
     get '/new_resident', to: 'users/registrations#new_resident', as: 'new_resident'
     get '/get_locations', to: 'users/registrations#get_locations', as: 'get_locations'
     get '/edit_volunteer', to: 'users/registrations#edit_volunteer', as: 'edit_volunteer'
     get '/edit_resident', to: 'users/registrations#edit_resident', as: 'edit_resident'
     get '/edit_organization', to: 'users/registrations#edit_organization', as: 'edit_organization'
  end
  root to: "home#index"
  resources :organizations
    get '/organizations/:id/surveys', to: 'organizations#view_surveys', as: 'view_surveys'
    get '/organizations/:id/surveys/:survey_id/assign_locations', to: 'organizations#assign_locations', as: 'assign_locations'
    post '/organizations/:id/surveys/:survey_id/assign', to: 'organizations#assign', as: 'assign'
    get '/organizations/:id/nest_locations', to: 'organizations#nest_locations', as: 'nest_locations'
    get '/organizations/:id/view_locations', to: 'organizations#view_locations', as: 'view_locations'
  resources :locations
  resources :surveys
    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview'
    post '/surveys/:id/create_responses', to: 'surveys#create_responses', as: 'create_responses'
    get '/surveys/:id/edit_responses', to: 'surveys#edit_responses', as: 'edit_responses'
    post '/surveys/:id/update_responses', to: 'surveys#update_responses', as: 'update_responses'
    get '/surveys/:id/delete_responses', to: 'surveys#delete_responses', as: 'delete_responses'
  resources :residents
  resources :volunteers
    get '/volunteers/:id/organizations/:org_id', to: 'volunteers#view_org', as: 'view_org'
    get '/volunteers/:id/add_organizations', to: 'volunteers#add_organizations', as: 'add_organizations'
    get '/volunteers/:id/add_locations', to: 'volunteers#add_locations', as: 'add_locations'
    post '/volunteers/:id/associate_locations', to: 'volunteers#associate_locations', as: 'associate_locations'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/remove_location', to: 'volunteers#remove_location', as: 'remove_vol_location'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/add_location', to: 'volunteers#add_vol_location', as: 'add_vol_location'
  resources :responses
  resources :matches
    get '/matches/match_detail/:match_id/:participant_id', to: 'matches#match_detail', as: 'match_detail'
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  has_and_belongs_to_many :locations
  has_many :responses
  has_many :matches
  belongs_to :user
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :load_volunteer, only: [:show, :edit, :update, :destroy, :view_org, :add_locations, :remove_location, :add_vol_location]
  before_action :volunteer_organizations, only: [:show]

  def index
    @volunteers = Volunteer.all
    if request.xhr?
      @organization = Organization.where(name: params['org_name'])[0]
      @locations = @organization.locations
      respond_to do |format|
        format.html
        format.json { render json: @locations }
      end
    end
  end

  def new
    @volunteer = Volunteer.new
  end

  def create
    @volunteer = Volunteer.new(
      birthdate: volunteer_params[:birthdate].to_date,
      phone_number: volunteer_params[:phone_number],
      user_id: session[:user_id]
    )
    if @volunteer.save
      session[:volunteer_id] = @volunteer.id
      redirect_to volunteer_path(@volunteer)
    else
      flash.now[:alert] = @volunteer.errors.full_messages
      render :new
    end
  end

  def show
    volunteer_organizations
  end

  def edit
    #code
  end

  def update
    if @volunteer.update_attributes(volunteer_params)
      redirect_to volunteer_path(@volunteer)
    else
      render :edit
    end
  end

  def destroy
    @volunteer.destroy
    redirect_to volunteers_path
  end

  def view_org
    @org = Organization.find(params[:org_id])
    @org_locations = @org.locations
    @volunteer = Volunteer.find(params[:id])
    @v_locations = @volunteer.locations.where(organization_id: @org.id)
    # byebug
    @org_surveys = []
    @org_locations.each do |loc|
      loc.surveys.each do |surv|
        @org_surveys << surv
      end
    end

    responses = @volunteer.responses
    @v_surveys = []
    responses.each do |r|
      @v_surveys << r.question.survey
    end
    @v_surveys = @v_surveys.uniq
  end

  def add_organizations

  end

  def remove_location
    @location = Location.find(params[:loc_id])
    @locations = @volunteer.locations
    @locations.delete(@location)
    redirect_to view_org_path(id: @volunteer.id, org_id: params[:org_id])
  end

  def add_vol_location
    @location = Location.find(params[:loc_id])
    @locations = @volunteer.locations
    @locations << @location
    redirect_to view_org_path(id: @volunteer.id, org_id: params[:org_id])
  end

  def add_locations
    volunteer_organizations
    @organization = Organization.new
    @organizations = Organization.all
    @uniq_organizations = (@organizations - @v_organizations).uniq
    # @organization = Organization.find(params[:organization][:name])
    # @locations = @organization.locations
    @new_location = Location.new
  end

  def associate_locations
    # byebug
    volunteer = Volunteer.find(params[:id])
    location_ids = params[:location][:branch_name]
    locations = []
    i = 1
    while i < location_ids.count
      locations << Location.find(location_ids[i])
      i+=1
    end
    locations.each do |loc|
      volunteer.locations << loc
    end
    redirect_to view_org_path(id: params[:id], org_id: params[:location][:organization_id])
  end

  private

  def volunteer_organizations
    @v_locations = @volunteer.locations
    @v_organizations = []
    @v_locations.each do |location|
      @v_organizations << location.organization
    end
    @v_organizations = @v_organizations.uniq
  end

  def volunteer_params
    params.require(:volunteer).permit(:birthdate, :phone_number, :user_id)
  end

  def load_volunteer
    @volunteer = Volunteer.find(params[:id])
  end

end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/add_locations.html.erb
<div class="row">
  <div class="col s12 center"><h2>Add A Location</h2></div>
</div>

<%= form_for(@new_location, url: associate_locations_path) do |f| %>

  <div class="input-field">
    <%= f.label :organization_id, "Name of Organization" %><br><br>
    <%= f.collection_select(:organization_id, @uniq_organizations, :id, :name) %>
  </div>

  <div class="input-field">
    <%= f.label :branch_name, "Location" %><br><br>
    <%= f.collection_select(:branch_name, Match.all, :id, :branch_name, { :prompt => "Select an organization" } , {:multiple => true}) %>
  </div>
  <div class="action form-submit">
    <%= f.submit "Add Location" %>
  </div>
<% end %>

app/views/volunteers/add_organizations.html.erb
<div class="row">
  <div class="col s12 center"><h2>Add an Organization</h2></div>
</div>

<%= form_for(@organization, url: add_locations_path, method: "get") do |f| %>
  <div class="input-field">
    <%= f.label :name, "Name of Organization" %><br>
    <%= f.collection_select(:name, @uniq_organizations, :id, :name) %>
  </div>
  <div class="input-field">
    <%= f.label :name, "Name of Organization" %>
    <%= f.collection_select(:name, @uniq_organizations, :id, :name) %>
  </div><br>
  <div class="action">
    <%= f.submit "Add Organization" %>
  </div>
<% end %>

app/views/volunteers/new.html.erb
<h1>Sign up as a Volunteer</h1>

<%= form_for(@volunteer, url: volunteers_path(@volunteer)) do |f| %>

  <div class="field">
    <%= f.label :birthdate, "Date of birth" %><br />
    <%= f.date_field :birthdate, {class: "datepicker"} %>
  </div>

  <div class="field">
    <%= f.label(:phone_number)%><br />
    <%= f.telephone_field(:phone_number) %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/volunteers/show.html.erb
<h6 class="edit-profile"><%= link_to "Edit Profile", edit_user_registration_path, class: "edit-profile" %></h6>

<!-- <div class="row">

  <div class="col s4 user-profile">
    <div class="profile name"><h4><%= @volunteer.user.first_name %> <%= @volunteer.user.last_name %></h4></div>
    <div class="profile image"><%= image_tag @volunteer.user.avatar, height: 100, width: 100 %></div>
  </div>


  <div class="col s8 dashboard">
    <div><%# @volunteer.locations.map { |loc| loc.organization }.uniq.count %> organizations</div>
    <div><%# @volunteer.locations.count %> locations</div>
    <div><%# @volunteer.responses.map { |res| res.survey }.uniq.count %> surveys</div>
  </div>
</div> -->

<div class="row">
  <div class="col s12 center"><h2> <%= @volunteer.user.first_name %> <%= @volunteer.user.last_name %>'s Organizations</h2></div>

  <div class="my-org">
  <% if @v_organizations.empty? %>
    <h5>You are not a part of any organizations yet. No better time to join some! </h5>
  <% else %>
  <% @v_organizations.each do |org| %>
    <div class="col s4 center">
      <div><%= link_to (image_tag org.user.avatar, height: 100, width: 100), view_org_path(:id => params[:id], :org_id => org.id)  %></div>
      <div class="full-width"><%= link_to org.name, view_org_path(:id => params[:id], :org_id => org.id), class: "waves-effect waves-light btn" %></div>
    </div>
  </div>
  <% end %>
  <% end %>
  <div class="col s12 center top-spacing"><%= link_to "Add Organizations", add_locations_path, class: "waves-effect waves-light btn-large" %></div>
</div>

app/views/volunteers/view_org.html.erb
<br><%= link_to "Back To Profile", volunteer_path(@volunteer), class: "back-to-profile" %>

<h2 class="formTitle"><%=@org.name%></h2>
<h4>Locations</h4>
<ol>
<% @org_locations.each do |loc| %>
  <h6><li><%= loc.branch_name %> |
  <% if @v_locations.include?(loc) %>
    <%= link_to "Remove Location", remove_vol_location_path(:id => params[:id], :org_id => params[:org_id], :loc_id => loc.id) %>
  </li></h6>
      <ul>
        <% loc.surveys.each do |surv| %>
          <li>
            <%= surv.name %> |
            <% if @v_surveys && @v_surveys.include?(surv) %>
              <%= link_to "Edit Responses", edit_responses_path(surv) %>,
              <%= link_to "Delete Responses", delete_responses_path(surv) %>
            <% else %>
              <%= link_to "Take Survey", survey_path(surv) %>
            <% end %>
          </li>
        <% end %>
      </ul>
  <% else %>
    <%= link_to "Add Location", add_vol_location_path(:id => params[:id], :org_id => params[:org_id], :loc_id => loc.id) %>
  </li></h6>
  <% end %>
<% end %>
</ol>