config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
     get '/register_type', to: 'users/registrations#register_type', as: 'register_type'
     get '/new_volunteer', to: 'users/registrations#new_volunteer', as: 'new_volunteer'
     get '/new_organization', to: 'users/registrations#new_organization', as: 'new_organization'
     get '/new_resident', to: 'users/registrations#new_resident', as: 'new_resident'
     get '/get_locations', to: 'users/registrations#get_locations', as: 'get_locations'
     get '/edit_volunteer', to: 'users/registrations#edit_volunteer', as: 'edit_volunteer'
     get '/edit_resident', to: 'users/registrations#edit_resident', as: 'edit_resident'
     get '/edit_organization', to: 'users/registrations#edit_organization', as: 'edit_organization'
  end
  root to: "home#index"
  resources :organizations
    get '/organizations/:id/surveys', to: 'organizations#view_surveys', as: 'view_surveys'
    get '/organizations/:id/surveys/:survey_id/assign_locations', to: 'organizations#assign_locations', as: 'assign_locations'
    post '/organizations/:id/surveys/:survey_id/assign', to: 'organizations#assign', as: 'assign'
    get '/organizations/:id/nest_locations', to: 'organizations#nest_locations', as: 'nest_locations'
    get '/organizations/:id/view_locations', to: 'organizations#view_locations', as: 'view_locations'
  resources :locations
  resources :surveys
    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview'
    post '/surveys/:id/create_responses', to: 'surveys#create_responses', as: 'create_responses'
    get '/surveys/:id/edit_responses', to: 'surveys#edit_responses', as: 'edit_responses'
    post '/surveys/:id/update_responses', to: 'surveys#update_responses', as: 'update_responses'
    get '/surveys/:id/delete_responses', to: 'surveys#delete_responses', as: 'delete_responses'
  resources :residents
  resources :volunteers
    get '/volunteers/:id/organizations/:org_id', to: 'volunteers#view_org', as: 'view_org'
    get '/volunteers/:id/add_organizations', to: 'volunteers#add_organizations', as: 'add_organizations'
    get '/volunteers/:id/add_locations', to: 'volunteers#add_locations', as: 'add_locations'
    post '/volunteers/:id/associate_locations', to: 'volunteers#associate_locations', as: 'associate_locations'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/remove_location', to: 'volunteers#remove_location', as: 'remove_vol_location'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/add_location', to: 'volunteers#add_vol_location', as: 'add_vol_location'
  resources :responses
  resources :matches
    get '/matches/match_detail/:match_id/:participant_id', to: 'matches#match_detail', as: 'match_detail'
end

app/models/resident.rb
class Resident < ApplicationRecord
  belongs_to :location
  has_many :responses
  has_many :matches
  belongs_to :user
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController

  before_action :load_resident, only: [:show, :edit, :update, :destroy]
  before_action :configure_form, only: [:new, :create]

  def index
    @residents = Resident.all
  end

  def new
    @resident = Resident.new
  end

  def create
    @resident = Resident.new(
      birthdate: params[:birthdate].to_date,
      location_id: params[:location_id],
      user_id: session[:user_id]
      )
    if @resident.save
      session[:resident] = @resident.id
      redirect_to resident_path(@resident)
    else
      flash.now[:alert] = @resident.errors.full_messages
      render :new
    end
  end

  def show
    @completed_surveys = []
    @resident.responses.each do |resp|
      @completed_surveys << resp.question.survey.id
    end
    @completed_surveys = @completed_surveys.uniq
  end

  def edit
    #code
  end

  def update
    if @resident.update_attributes(resident_params)
      redirect_to resident_path(@resident)
    else
      render :edit
    end
  end

  def destroy
    @resident.destroy
    redirect_to residents_path
  end

  private

  def resident_params
    params.require(:resident).permit(:birthdate, :location_id, :user_id)
  end

  def load_resident
    @resident = Resident.find(params[:id])
  end

  def configure_form
    @resident = Resident.new
    @organizations = Organization.all
    @locations = [['SV',1],['RS',2]]
  end

end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/residents/new.html.erb
<h2>Sign up as a resident</h2>

<div class="resident-new-form">
  <%= form_tag residents_path(@resident) do %>
    <div class="field">
      <%= label_tag :birthdate, "Date of birth" %><br />
      <%= date_field_tag :birthdate, {class: "datepicker"} %>
    </div>

    <div class="field">
      <%= label_tag :organization_id, "What organization are you a resident with?"%><br/>
      <%= select_tag 'Organizations', options_from_collection_for_select(@organizations, "id", "name"), prompt: "Select an Organization" %>
    </div>
</div>

    <div class="actions">
      <%= submit_tag "Sign up" %>
    </div>
  <% end %>

app/views/residents/show.html.erb
<div class="res-show-container">
  <div class="profile-res">
  <!-- <div class="name-container"> -->
    <h4 class="res-show-name"> <%= User.find(@resident.user_id).first_name %> <%= User.find(@resident.user_id).last_name %></h4>
  <!-- </div> -->
  <div class="res-avatar">
    <%= image_tag User.find(@resident.user_id).avatar.url(:medium), :class=>"profilePhoto" %>
  </div>
</div>
  <div class="res-home">

    <div class="res-info-container">
      <div class="res-left">
        <div class="res-org-name">
          <b>Organization </b>: <%= Organization.find(@resident.location.organization_id).name %>
        </div><br>

        <div class="res-loc-name">
          <b>Location</b>: <%= @resident.location.branch_name %>
        </div>
      </div>

      <div class="res-right">
        <div class="surveys">
          <b>Surveys</b><br><br>
          <% Organization.find(@resident.location.organization_id).surveys.each do |surv| %>
          <div class="surv">
            <%= surv.name %>
            <% if @completed_surveys.include?(surv.id) %>
              <%= link_to 'Edit', edit_responses_path(surv), :class =>'res-edit-surv' %> <%= link_to 'Delete', delete_responses_path(surv), :class =>'res-del-surv' %><br><br><br>
            <% else %>
              <%= link_to "Take", survey_path(surv), :class =>'res-take-surv' %><br><br><br>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>

    <div class="edit-res-profile">
    <%= link_to "Edit Profile", edit_user_registration_path, :class => "edit-res-link" %>
    </div>
  </div>
</div>

<!-- <div class="delete-res-profile"> -->
<%# link_to "Delete Profile", delete_user_registration_path %> <!--Need to get path for deleting account-->
<!-- </div> -->