config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
     get '/register_type', to: 'users/registrations#register_type', as: 'register_type'
     get '/new_volunteer', to: 'users/registrations#new_volunteer', as: 'new_volunteer'
     get '/new_organization', to: 'users/registrations#new_organization', as: 'new_organization'
     get '/new_resident', to: 'users/registrations#new_resident', as: 'new_resident'
     get '/get_locations', to: 'users/registrations#get_locations', as: 'get_locations'
     get '/edit_volunteer', to: 'users/registrations#edit_volunteer', as: 'edit_volunteer'
     get '/edit_resident', to: 'users/registrations#edit_resident', as: 'edit_resident'
     get '/edit_organization', to: 'users/registrations#edit_organization', as: 'edit_organization'
  end
  root to: "home#index"
  resources :organizations
    get '/organizations/:id/surveys', to: 'organizations#view_surveys', as: 'view_surveys'
    get '/organizations/:id/surveys/:survey_id/assign_locations', to: 'organizations#assign_locations', as: 'assign_locations'
    post '/organizations/:id/surveys/:survey_id/assign', to: 'organizations#assign', as: 'assign'
    get '/organizations/:id/nest_locations', to: 'organizations#nest_locations', as: 'nest_locations'
    get '/organizations/:id/view_locations', to: 'organizations#view_locations', as: 'view_locations'
  resources :locations
  resources :surveys
    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview'
    post '/surveys/:id/create_responses', to: 'surveys#create_responses', as: 'create_responses'
    get '/surveys/:id/edit_responses', to: 'surveys#edit_responses', as: 'edit_responses'
    post '/surveys/:id/update_responses', to: 'surveys#update_responses', as: 'update_responses'
    get '/surveys/:id/delete_responses', to: 'surveys#delete_responses', as: 'delete_responses'
  resources :residents
  resources :volunteers
    get '/volunteers/:id/organizations/:org_id', to: 'volunteers#view_org', as: 'view_org'
    get '/volunteers/:id/add_organizations', to: 'volunteers#add_organizations', as: 'add_organizations'
    get '/volunteers/:id/add_locations', to: 'volunteers#add_locations', as: 'add_locations'
    post '/volunteers/:id/associate_locations', to: 'volunteers#associate_locations', as: 'associate_locations'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/remove_location', to: 'volunteers#remove_location', as: 'remove_vol_location'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/add_location', to: 'volunteers#add_vol_location', as: 'add_vol_location'
  resources :responses
  resources :matches
    get '/matches/match_detail/:match_id/:participant_id', to: 'matches#match_detail', as: 'match_detail'
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_and_belongs_to_many :locations
  has_many :questions, inverse_of: :survey
  has_many :responses, through: :questions
  belongs_to :organization, optional: true 

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :load_survey, only: [:show, :edit, :update, :destroy, :show, :preview, :delete_responses, :edit_responses]
  before_action :load_question_types, only: [:new, :create, :edit]
  before_action :question_set, only: [:show, :preview]
  before_action :load_respondent, only: [:show, :edit_responses, :delete_responses]
  before_action :load_organization, only: [:show, :edit_responses, :delete_responses]
  before_action :load_questions, only: [:edit_responses, :delete_responses]

  def index
    @surveys = Survey.all
  end

  def new
    @survey = Survey.new
    @organizations = Organization.all
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.organization_id = session[:organization_id] #we should be testing by logging in as an organization
    if @survey.save
      redirect_to preview_path(@survey) #Change this once you decide user flows.
    else
      render :new
    end
  end

  def show
    num_questions = @survey.questions.count
    @responses = []
    num_questions.times do
      @responses << Response.new
    end
    @q_counter = 0
  end

  def create_responses
    params["responses"].each do |response|

      if response[:response].is_a? Array
        Response.create(
          question_id: response_params(response)[:question_id],
          volunteer_id: response_params(response)[:volunteer_id],
          resident_id: response_params(response)[:resident_id],
          response: response_params(response)[:response].reject(&:empty?).join(', ')
        )
      else
        Response.create(response_params(response))
      end
    end
    if session[:volunteer_id]
      redirect_to view_org_path(id: session[:volunteer_id], org_id: params[:organization_id])
    elsif session[:resident_id]
      redirect_to resident_path(session[:resident_id])
    else
      redirect_to root_url #not sure where this should go atm
    end
  end

  def edit
      @organizations = Organization.all
  end

  def update
    if @survey.update_attributes(survey_params)
      redirect_to preview_path(@survey) #Change this once you decide user flows.
      # organization_url(Organization.find(session[:organization_id]))
    else
      render :edit
    end
  end

  def destroy
    @survey.destroy
    redirect_to organization_path(Organization.where(user_id: session[:user_id])[0])
  end

  def preview
  end

  def edit_responses
    @responses = []
    @question_set = []
    @questions.each do |q|
      answers = []
      q.answer_sets.each do |a|
        answers << a
      end
      if session[:volunteer_id]
        response = q.responses.where(volunteer_id: @respondent).take
      elsif session[:resident_id]
        response = q.responses.where(resident_id: @respondent).take
      end
      response_ids = []
      response.response.split(', ').each do |r|
        response_ids << AnswerSet.where(question_id: q.id, answer: r).take.answer if AnswerSet.where(question_id: q.id, answer: r).take
      end
      @question_set << [q, answers, response_ids]
      @responses << response
    end
    @q_counter = 0
  end

  def update_responses
    params["responses"].each do |id, edits|
      response = Response.find(id)
      if edits[:response].is_a? Array
        response.update(
          response: response_params(edits)[:response].reject(&:empty?).join(', ')
        )
      else
        response.update(response_params(edits))
      end
    end

    if session[:volunteer_id]
      redirect_to view_org_path(id: session[:volunteer_id], org_id: params[:organization_id]) #update this based on who is responding to the survey
    elsif session[:resident_id]
      redirect_to resident_path(session[:resident_id])
    end
  end

  def delete_responses
    @responses = []
    @questions.each do |q|
      if session[:volunteer_id]
        response = q.responses.where(volunteer_id: @respondent).take
      elsif session[:resident_id]
        response = q.responses.where(resident_id: @respondent).take
      end
      @responses << response
    end
    @responses.each do |response|
      response.delete
    end

    if session[:volunteer_id]
      redirect_to view_org_path(id: session[:volunteer_id], org_id: @organization.id) #update this based on who is responding to the survey
    elsif session[:resident_id]
      redirect_to resident_path(session[:resident_id])
    end
  end

private

  def question_set
    @question_set = []
    @survey.questions.each do |q|
      answers = []
      q.answer_sets.each do |a|
        answers << a
      end
      @question_set << [q, answers]
    end
    @question_set
  end

  def survey_params
    params.require(:survey).permit(
    :name, :organization_id,
    questions_attributes: [:id, :survey_id, :question, :question_type, :ranking, :_destroy, answer_sets_attributes: [:id, :question_id, :answer, :_destroy]]
    )
  end

  def load_respondent
    if session[:volunteer_id]
      @respondent = session[:volunteer_id]
    elsif session[:resident_id]
      @respondent = session[:resident_id]
    end
  end

  def response_params(r_params)
    if r_params[:response].is_a? Array
      r_params.permit(:response_id, :question_id, {:response => []}, :volunteer_id, :resident_id, :organization_id)
    else
      r_params.permit(:response_id, :question_id, :response, :volunteer_id, :resident_id, :organization_id)
    end
  end

  def load_survey
    @survey = Survey.find(params[:id])
  end

  def load_question_types
    @question_types = ['Multiple Choice Question', 'Drop-Down Question', 'Open Response Question', 'Display Text']
  end

  def load_organization
    @organization = @survey.organization
  end

  def load_questions
    @questions = @survey.questions
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer_set_fields.html.erb
<div class="nested-fields">

  <div class="field">
    <%= f.label :answer, "What responses would you like respondents to choose from?" %>
    <%= f.text_field :answer, placeholder: "Potential Response"%>
  </div>

  <div style="text-align:right">
    <%= link_to_remove_association "Remove Answer", f %>
  </div>

</div>

app/views/surveys/_question_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :question_type, "What type of content would you like to add?", class: "survey-creation-labels" %>
    <%= f.select(:question_type, @question_types, {:prompt => "Select A Content Type"}, {:class => 'browser-default dropdown question_type_dropdown'})  %>
  </div>

  <div class="field question_description">
    <%= f.label :question, "What question would you like to ask?", class: "survey-creation-labels" %>
    <%= f.text_field :question %>
  </div>

  <div class="range-field">
    <%= f.label :ranking, "How important is this for matching?", class: "survey-creation-labels" %>
    <%= f.range_field :ranking, min: 0, max: 100 %>
  </div>

  <div class="add-question-fields">
    <%= f.fields_for :answer_sets do |answer_set| %>
      <%= render 'answer_set_fields', f: answer_set %>
    <% end %>
    <br>
    <%= link_to_add_association "Add Answers To Choose From", f, :answer_sets %>
  </div>

  <div class="remove-content">
    <%= link_to_remove_association "Remove Content", f %>
  </div>
</div>

app/views/surveys/edit.html.erb
<div class="spacingDiv80"></div>

<div class="formContainer">

  <%= form_for @survey do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="add-question-fields">
      <%= f.fields_for :questions do |question| %>
        <%= render 'question_fields', f: question %>
      <% end %>
      <%= link_to_add_association "Add question", f, :questions %>
    </div>
    <br /><div class="action form-submit">
      <%= f.submit "Save Survey" %>
    </div>
  <% end %>

</div>

<div class="spacingDiv80"></div>

app/views/surveys/edit_responses.html.erb
<h2 class="formTitle"> Edit Responses </h2>

<%= form_tag update_responses_path do %>
  <% @responses.each do |response| %>
    <% question = @question_set[@q_counter] %>

    <%= fields_for 'responses[]', response do |r| %>
      <% if question[0].question_type == "Open Response Question" %>
        <% if session[:volunteer_id] %>
          <%= r.hidden_field :volunteer_id, value: @respondent %>
        <% elsif session[:resident_id] %>
          <%= r.hidden_field :resident_id, value: @respondent %>
        <% end %>
        <div class="input-field">
          <%= r.label :question_id, question[0].question %><br>
          <%= r.hidden_field :question_id, value: question[0].id %>
        </div>
        <div class="input-field">
          <%= r.text_field :response %>
        </div>

      <% elsif question[0].question_type == "Multiple Choice Question" %>
        <% if session[:volunteer_id] %>
          <%= r.hidden_field :volunteer_id, value: @respondent %>
        <% elsif session[:resident_id] %>
          <%= r.hidden_field :resident_id, value: @respondent %>
        <% end %>
        <div class="input-field">
          <%= r.label :question_id, question[0].question %><br>
          <%= r.hidden_field :question_id, value: question[0].id %>
        </div>
        <div class="input-field">
          <br><br>
          <%= r.collection_select(:response, question[1], :answer, :answer, {:selected => question[2]}, {:multiple => true})%>
        </div>

      <% else %>
        <% if session[:volunteer_id] %>
          <%= r.hidden_field :volunteer_id, value: @respondent %>
        <% elsif session[:resident_id] %>
          <%= r.hidden_field :resident_id, value: @respondent %>
        <% end %>
        <div class="input-field">
          <%= r.label :question_id, question[0].question %><br>
          <%= r.hidden_field :question_id, value: question[0].id %>
        </div>
        <div class="input-field">
          <br><br>
          <%= r.collection_select :response, question[1], :id, :answer %>
        </div>
      <% end %>
    <% end %>
    <% @q_counter += 1 %>
  <% end %>

  <%= hidden_field_tag :organization_id, @organization.id %>

  <button class="btn edit-resp" type="submit" name="action">
    Submit
  </button>

<% end %>

app/views/surveys/index.html.erb
  <% @surveys.each do |survey| %>
  <div>
    <%= link_to survey.name, survey_path(survey) %>
  </div>
  <% end %>

app/views/surveys/new.html.erb
<h3 class="formTitle">Create a new survey</h3>
<!-- <div class="spacingDiv80"></div> -->

<div class="formContainer">

  <%= form_for @survey do |f| %>
  <div class="field">
    <%= f.label :name, "What would you like to name your survey?", class: "survey-creation-labels" %>
    <%= f.text_field :name %>
  </div>
  <div class="add-question-fields">
    <%= f.fields_for :questions do |question| %>
    <%= render 'question_fields', f: question %>
    <% end %>
    <%= link_to_add_association "Add Content", f, :questions, class: "add-content" %>
  </div><br><br>
  <div class="action">
    <%= f.submit "Submit Survey", class: "new-survey-submit" %>
  </div>
<% end %>

</div>

<div class="spacingDiv80"></div>

app/views/surveys/preview.html.erb
<div class="spacingDiv80"></div>

<div class="formContainer previewContainer">

  <h3 class="voloGreen"><%= @survey.name %></h3><br />

<div class="survey-result">

  <%= form_tag %>
  <% @question_set.each do |q| %>
    <% question_number = @question_set.index(q) + 1 %>
    <h6><%= question_number%> <%=q[0].question %></h6>
    <% if q[0].question_type == "Multiple Choice Question" %>
      <div class="row">
        <div class="col s7 field input-field">
          <% answers = [] %>
          <% q[1].each do |a| %>
            <% answers << a.answer %>
          <% end %>
          <%= select_tag q[0].question, options_for_select(answers),  multiple: true %>
        </div>
        <div class="col s4">
          <h6 class="voloYellow rankingPreview"> Ranking: <%= q[0].ranking %> </h6>
        </div>
      </div>

    <% elsif q[0].question_type == "Drop-Down Question" %>
      <div class="row">
        <div class="col s7 field input-field">
          <% answers = [] %>
          <% q[1].each do |a| %>
            <% answers << a.answer %>
          <% end %>
          <%= select_tag q[0].question, options_for_select(answers) %>
        </div>
        <div class="col s4">
          <h6 class="voloYellow rankingPreview"> Ranking: <%= q[0].ranking %> </h6>
        </div>
      </div>
    <% elsif q[0].question_type == "Open Response Question" %>
      <div class="row">
        <div class="col s7 field input-field">
          <%= text_field_tag q[0].question %>
        </div>
        <!-- <div class="col s4">
          <h6 class="voloYellow rankingPreview"> Ranking: <%= q[0].ranking %> </h6>
        </div> -->
      </div>
    <% end %>
    <% end %>

    <br />

<div class="col s11 result-button">
  <%= link_to "Complete Survey", organization_path(Organization.find(session[:organization_id])), :class=>"completeSurveyPreview" %>
  <%= link_to "Edit Survey", edit_survey_path(@survey), :class=>"editSurveyPreview" %>
</div>

</div>

</div>

<div class="spacingDiv80"></div>

app/views/surveys/show.html.erb
<div class="surv-top">
  <h3><%= @survey.organization.name %></h3>
  <h4><%= @survey.name %></h4>
</div>

<%= form_tag create_responses_path do %>
  <% @responses.each do |response| %>
    <% question = @question_set[@q_counter] %>

    <%= fields_for 'responses[]', response do |r| %>
      <% if question[0].question_type == "Open Response Question" %>
        <% if session[:volunteer_id] %>
          <%= r.hidden_field :volunteer_id, value: @respondent %>
        <% elsif session[:resident_id] %>
          <%= r.hidden_field :resident_id, value: @respondent %>
        <% end %>
        <div class="input-field">
          <%= r.label :question_id, question[0].question %><br>
          <%= r.hidden_field :question_id, value: question[0].id %>
        </div>
        <div class="input-field">
          <%= r.text_field :response %>
        </div>

      <% elsif question[0].question_type == "Multiple Choice Question" %>
        <% if session[:volunteer_id] %>
          <%= r.hidden_field :volunteer_id, value: @respondent %>
        <% elsif session[:resident_id] %>
          <%= r.hidden_field :resident_id, value: @respondent %>
        <% end %>
        <div class="input-field">
          <%= r.label :question_id, question[0].question %><br>
          <%= r.hidden_field :question_id, value: question[0].id %>
        </div>
        <div class="input-field">
          <br><br>
          <%= r.collection_select(:response, question[1], :answer, :answer, {prompt: "Please select"}, {:multiple => true} )%>
        </div>

      <% elsif question[0].question_type == "Drop-Down Question" %>
        <% if session[:volunteer_id] %>
          <%= r.hidden_field :volunteer_id, value: @respondent %>
        <% elsif session[:resident_id] %>
          <%= r.hidden_field :resident_id, value: @respondent %>
        <% end %>
        <div class="input-field">
          <%= r.label :question_id, question[0].question %><br>
          <%= r.hidden_field :question_id, value: question[0].id %>
        </div>
        <div class="input-field">
          <br><br>
          <%= r.collection_select :response, question[1], :id, :answer %>
        </div>
      <% else %>
      <div class="input-field">
        <%= r.label :question_id, question[0].question %><br>
      </div><br><br>
      <% end %>
    <% end %>
    <% @q_counter += 1 %>
  <% end %>

  <%= hidden_field_tag :organization_id, @organization.id %>

  <button class="btn surv-submit" type="submit" name="action">
    Submit
  </button><br>

<% end %>