config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  devise_scope :user do
     get '/register_type', to: 'users/registrations#register_type', as: 'register_type'
     get '/new_volunteer', to: 'users/registrations#new_volunteer', as: 'new_volunteer'
     get '/new_organization', to: 'users/registrations#new_organization', as: 'new_organization'
     get '/new_resident', to: 'users/registrations#new_resident', as: 'new_resident'
     get '/get_locations', to: 'users/registrations#get_locations', as: 'get_locations'
     get '/edit_volunteer', to: 'users/registrations#edit_volunteer', as: 'edit_volunteer'
     get '/edit_resident', to: 'users/registrations#edit_resident', as: 'edit_resident'
     get '/edit_organization', to: 'users/registrations#edit_organization', as: 'edit_organization'
  end
  root to: "home#index"
  resources :organizations
    get '/organizations/:id/surveys', to: 'organizations#view_surveys', as: 'view_surveys'
    get '/organizations/:id/surveys/:survey_id/assign_locations', to: 'organizations#assign_locations', as: 'assign_locations'
    post '/organizations/:id/surveys/:survey_id/assign', to: 'organizations#assign', as: 'assign'
    get '/organizations/:id/nest_locations', to: 'organizations#nest_locations', as: 'nest_locations'
    get '/organizations/:id/view_locations', to: 'organizations#view_locations', as: 'view_locations'
  resources :locations
  resources :surveys
    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview'
    post '/surveys/:id/create_responses', to: 'surveys#create_responses', as: 'create_responses'
    get '/surveys/:id/edit_responses', to: 'surveys#edit_responses', as: 'edit_responses'
    post '/surveys/:id/update_responses', to: 'surveys#update_responses', as: 'update_responses'
    get '/surveys/:id/delete_responses', to: 'surveys#delete_responses', as: 'delete_responses'
  resources :residents
  resources :volunteers
    get '/volunteers/:id/organizations/:org_id', to: 'volunteers#view_org', as: 'view_org'
    get '/volunteers/:id/add_organizations', to: 'volunteers#add_organizations', as: 'add_organizations'
    get '/volunteers/:id/add_locations', to: 'volunteers#add_locations', as: 'add_locations'
    post '/volunteers/:id/associate_locations', to: 'volunteers#associate_locations', as: 'associate_locations'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/remove_location', to: 'volunteers#remove_location', as: 'remove_vol_location'
    get '/volunteers/:id/organizations/:org_id/locations/:loc_id/add_location', to: 'volunteers#add_vol_location', as: 'add_vol_location'
  resources :responses
  resources :matches
    get '/matches/match_detail/:match_id/:participant_id', to: 'matches#match_detail', as: 'match_detail'
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :locations, inverse_of: :organization
  belongs_to :user
  accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true
  has_many :surveys
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :load_organization, only: [:show, :edit, :update, :destroy, :view_surveys, :assign_locations, :nest_locations, :view_locations]

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(
      location: organization_params[:location],
      phone_number: organization_params[:phone_number],
      user_id: session[:user_id],
      name: "#{User.find(session[:user_id]).first_name} #{User.find(session[:user_id]).last_name}"
    )

    if @organization.save
      @organization.name =
      session[:organization_id] = @organization.id
      redirect_to organization_path(@organization)
    else
      flash.now[:alert] = @organization.errors.full_messages
      render :new
    end
  end

  def show

    @current_organization_id = session[:organization_id]
    @surveys = Survey.where(organization_id: @current_organization_id)
    @locations = @organization.locations

    @residents = []
    @locations.each do |loc|
      loc.residents.each do |res|
        @residents << res
      end
    end
    @residents = @residents.uniq

    @volunteers = []
    @locations.each do |loc|
      loc.volunteers.each do |vol|
        @volunteers << vol
      end
    end
    @volunteers = @volunteers.uniq

  end


  def edit
    #code
  end

  def update
    if @organization.update_attributes(organization_params)
      redirect_to organization_path(@organization)
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path
  end

  def view_surveys
    @surveys = @organization.surveys
  end

  def assign_locations
    @organization = Organization.find(@organization)
    @location = Location.new
    @survey = Survey.find(params[:survey_id])
    @selected = []
    @survey.locations.each do |loc|
      @selected << loc.id
    end
  end

  def assign
    @survey = Survey.find(params[:survey_id])
    @survey.locations.delete_all
    params[:branch_name].each do |loc|
      @survey.locations << Location.find(loc) if !loc.empty?
    end
    redirect_to organization_path(params[:id])
  end

  def nest_locations

  end

  def view_locations
    #code
  end

  private

  def organization_params
    params.require(:organization).permit(:location, :phone_number, :user_id,
    locations_attributes:[:id, :branch_name, :address, :phone_number, :volunteer_coordinator_name,
    :volunteer_coordinator_phone, :organization_id, :_destroy])
  end

  def load_organization
    @organization = Organization.find(params[:id])
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_location_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :Location_name %>
    <%= f.text_field :branch_name  %>
  </div>

  <div class="field">
    <%= f.label :Address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :Phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :volunteer_coordinator_name, 'Volunteer Coordinator name' %>
    <%= f.text_field :volunteer_coordinator_name %>
  </div>

  <div class="field">
    <%= f.label :volunteer_coordinator_phone, 'Volunteer Coordinator phone number' %>
    <%= f.text_field :volunteer_coordinator_phone %>
  </div>

  <div style="text-align:right">
    <%= link_to_remove_association "Remove location", f %>
  </div>
</div>

app/views/organizations/assign_locations.html.erb
<div class="spacingDiv80"></div>

<div class="formContainer">

  <h5><%= @survey.name %></h5>

  <p>Assign Locations</p>

  <%= form_tag assign_path do%>
  <%= label_tag :branch_name, "Location" %>
  <%= select_tag :branch_name, options_from_collection_for_select(@organization.locations, "id", "branch_name", @selected), multiple: true %>
  <%= submit_tag %>
  <% end %>

</div>


<div class="spacingDiv80"></div>

app/views/organizations/nest_locations.html.erb
<div class="spacingDiv80"></div>

<div class="formContainer">

  <%= form_for @organization do |f| %>
  <div class="add-location-fields">
    <%= f.fields_for :locations do |location| %>
    <%= render 'location_fields', f: location %>
    <% end %>
    <div class="add-org-location">
      <%= link_to_add_association "Add location", f, :locations %>
    </div>
  </div><br>
  <div class="action form-submit">
    <%= f.submit "Save Locations" %>
  </div>
  <% end %>

</div>



<div class="spacingDiv80"></div>

app/views/organizations/new.html.erb
<h1>Sign up as an Organization</h1>

<%= form_for(@organization, url: organizations_path(@organization)) do |f| %>

  <div class="field">
    <%= f.label :location, 'Head Office Location' %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label(:phone_number)%><br />
    <%= f.telephone_field(:phone_number) %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/organizations/show.html.erb
<div class="profileDash">

  <%= image_tag User.find(@organization.user_id).avatar.url(:medium), :class=>"profilePhoto" %>
  <div class="org-name">
    <% if User.find(@organization.user_id).first_name %>
    <%= User.find(@organization.user_id).first_name %>
    <% end %>
    <% if User.find(@organization.user_id).last_name %>
    <%= User.find(@organization.user_id).last_name %>
    <% end %>
  </div>
    <div class="orgStats">
      <div class="orgTotals">
        <span class="totalText"><%=@locations.count%></span><br>
         Locations
       </div>
      <div class="orgTotals">
        <span class="totalText"><%=@residents.count %></span><br>
        Residents
      </div>
      <div class="orgTotals">
        <span class="totalText"><%=@volunteers.count %></span><br>
        Volunteers
      </div>
    </div>

  <%= link_to "Edit Profile", edit_user_registration_path, :class=>"profileDashEdit" %>

  <div class="create-match white-text text-darken-2">
    <%= link_to "Match", new_match_path, class: "match-button" %>
  </div>
</div>




<div class="organizationSurveys" style="position:relative">


<div class="leftDash">

  <div class="create-survey">
    <%= link_to "Create a Survey", new_survey_path, class: "create-survey-text"%>
  </div>

  <div class="add-edit-locations">
    <% if @organization.locations.empty? %>
    <%= link_to 'Add Locations', nest_locations_path, class: "add-edit-location-text" %>
    <% else %>
    <%= link_to 'Add/Edit Locations', nest_locations_path, class: "add-edit-location-text" %>
    <% end %>
  </div>

  <div class="view-org-locations">
    <%= link_to 'View Locations', view_locations_path %>
  </div>

</div>

<div class="rightDash">

  <div class="surveysOverallTitle">Surveys</div>

  <% @surveys.each do |survey| %>
    <div class="surveyName">
      <div class="surveyTitle">
      <%= survey.name %>
      </div>
      <div class="surveyView">
      <%= link_to "View", preview_path(survey.id), class: "greenText" %>
      </div>
      <div class="surveyEdit">
      <%= link_to 'Edit', edit_survey_path(survey.id), class: "greenText" %>
      </div>

    </div>
  <% end %>





</div>


</div>


<div class=spacingDiv80>

</div>

app/views/organizations/view_locations.html.erb
<div class="spacingDiv80"></div>

<div class="formContainer">

  <div>
    <h2 class="formTitle"><%= User.find(@organization.user_id).first_name %> <%= User.find(@organization.user_id).last_name %>' Locations</h2>
  </div>

  <% @organization.locations.each do |loc| %>
  <%= link_to location_path(loc) do %>
  <div class="location details">
    Branch name: <%= loc.branch_name %><br>
    Adress: <%= loc.address %><br>
    Phone Number: <%= loc.phone_number %><br>
    Volunteer Coordinator Name: <%= loc.volunteer_coordinator_name %><br>
    Volunteer Coordinator Phone Number: <%= loc.volunteer_coordinator_phone %>
  </div><br><br>
  <% end %>
  <% end %>

</div>

<div class="spacingDiv80"></div>

app/views/organizations/view_surveys.html.erb
<% if @surveys.empty? %>
  <h3>There are no surveys to display at the moment. Create some!</h3>
<% else %>
  <ol>
    <% @surveys.each do |survey| %>
      <li> <%= link_to survey.name, preview_path(survey) %> <%= link_to 'Delete Survey', survey_path(survey), data: {:confirm => 'Are you sure?'}, :method => :delete %></li>
        <ul>
          <li> <%= link_to "Assign Locations", assign_locations_path(id: params[:id], survey_id: survey.id) %> </li>
        </ul>
    <% end %>
  </ol>
<% end %>